# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

        #
        #Functions
        #

        def checkFields(self):
                textlogin = ""
                textsenha = ""

                def showMessage(Message):
                        self.popup.show()
                        self.label_error.setText(Message)

                #Check Login
                if not self.lineEdit_login.text():
                        textlogin = " Login vazio."
                else:
                        textlogin = ""

                #Check Senha
                if not self.lineEdit_senha.text():
                        textsenha = " Senha Vazia."
                else:
                        textsenha = ""

                #Check fields
                if textlogin + textsenha != '':
                        text = textlogin + textsenha
                        showMessage(text)
                else:
                        text = "Login Ok."
                        if self.checkBox.isChecked():
                                text = text + "| Login Salvo"
                        showMessage(text)

                

                                
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(838, 570)
                MainWindow.setMinimumSize(QtCore.QSize(600, 500))
                MainWindow.setStyleSheet("color: rgb(200, 200, 200);\n"
        "background-color: black;")
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
                self.verticalLayout.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout.setSpacing(0)
                self.verticalLayout.setObjectName("verticalLayout")
                self.header = QtWidgets.QFrame(self.centralwidget)
                self.header.setMaximumSize(QtCore.QSize(16777215, 35))
                self.header.setStyleSheet("")
                self.header.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.header.setFrameShadow(QtWidgets.QFrame.Raised)
                self.header.setObjectName("header")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
                self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_2.setSpacing(0)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.popup = QtWidgets.QFrame(self.header)
                self.popup.setMaximumSize(QtCore.QSize(450, 25))
                self.popup.setStyleSheet("background-color: rgb(255, 38, 42);\n"
        "border-radius: 5px;")
                self.popup.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.popup.setFrameShadow(QtWidgets.QFrame.Raised)
                self.popup.setObjectName("popup")
                self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.popup)
                self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
                self.horizontalLayout_3.setSpacing(0)
                self.horizontalLayout_3.setObjectName("horizontalLayout_3")
                self.label_error = QtWidgets.QLabel(self.popup)
                self.label_error.setAlignment(QtCore.Qt.AlignCenter)
                self.label_error.setObjectName("label_error")
                self.horizontalLayout_3.addWidget(self.label_error)
                self.X = QtWidgets.QPushButton(self.popup)
                self.X.setMaximumSize(QtCore.QSize(25, 25))
                self.X.setStyleSheet("QPushButton{\n"
        "    border-radius: 5px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    background-color: black;\n"
        "    color: white;\n"
        "}\n"
        "QPushButton:pressed{\n"
        "    background-color: white;\n"
        "    color: black;\n"
        "}")
                self.X.setObjectName("X")
                self.horizontalLayout_3.addWidget(self.X)
                self.horizontalLayout_2.addWidget(self.popup)
                self.verticalLayout.addWidget(self.header)
                self.frame_3 = QtWidgets.QFrame(self.centralwidget)
                self.frame_3.setStyleSheet("")
                self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_3.setObjectName("frame_3")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
                self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout.setSpacing(0)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.login = QtWidgets.QFrame(self.frame_3)
                self.login.setMaximumSize(QtCore.QSize(458, 550))
                self.login.setStyleSheet("background-color: rgb(0, 0, 0);")
                self.login.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.login.setFrameShadow(QtWidgets.QFrame.Plain)
                self.login.setObjectName("login")
                self.lineEdit_login = QtWidgets.QLineEdit(self.login)
                self.lineEdit_login.setGeometry(QtCore.QRect(120, 300, 220, 40))
                self.lineEdit_login.setMaximumSize(QtCore.QSize(220, 40))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.lineEdit_login.setFont(font)
                self.lineEdit_login.setStyleSheet("QLineEdit{\n"
        "    border-radius: 10px;\n"
        "    border: 2px solid #363636;\n"
        "    background-color: rgb(44, 44, 44);\n"
        "    padding-left: 10px;\n"
        "    color: rgb(185, 185, 185);\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 2px solid #c7c7c7;\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid #c7c7c7;\n"
        "}\n"
        "\n"
        "\n"
        "")
                self.lineEdit_login.setInputMask("")
                self.lineEdit_login.setText("")
                self.lineEdit_login.setFrame(True)
                self.lineEdit_login.setDragEnabled(False)
                self.lineEdit_login.setReadOnly(False)
                self.lineEdit_login.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
                self.lineEdit_login.setClearButtonEnabled(False)
                self.lineEdit_login.setObjectName("lineEdit_login")
                self.lineEdit_senha = QtWidgets.QLineEdit(self.login)
                self.lineEdit_senha.setGeometry(QtCore.QRect(120, 350, 220, 40))
                self.lineEdit_senha.setMaximumSize(QtCore.QSize(220, 40))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.lineEdit_senha.setFont(font)
                self.lineEdit_senha.setStyleSheet("QLineEdit{\n"
        "    border-radius: 10px;\n"
        "    border: 2px solid #363636;\n"
        "    background-color: rgb(44, 44, 44);\n"
        "    padding-left: 10px;\n"
        "    color: rgb(185, 185, 185);\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 2px solid #c7c7c7;\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid #c7c7c7;\n"
        "}")
                self.lineEdit_senha.setInputMask("")
                self.lineEdit_senha.setText("")
                self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.Password)
                self.lineEdit_senha.setObjectName("lineEdit_senha")
                self.checkBox = QtWidgets.QCheckBox(self.login)
                self.checkBox.setGeometry(QtCore.QRect(120, 400, 201, 31))
                font = QtGui.QFont()
                font.setPointSize(11)
                font.setBold(False)
                font.setUnderline(False)
                font.setStrikeOut(False)
                font.setKerning(True)
                self.checkBox.setFont(font)
                self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.checkBox.setAutoFillBackground(False)
                self.checkBox.setStyleSheet("QCheckBox::indicator{\n"
        "    border: 3px solid rgb(100, 100, 100);\n"
        "    width: 15px;\n"
        "    height: 15px;\n"
        "    border-radius: 10px;\n"
        "    background-color: rgb(50, 50, 50);\n"
        "}\n"
        "QCheckBox::indicator:hover{\n"
        "    background-color: rgb(200, 200, 200);\n"
        "}\n"
        "QCheckBox::indicator:checked{\n"
        "    background-color: rgb(200, 200, 200);\n"
        "}")
                self.checkBox.setChecked(False)
                self.checkBox.setAutoRepeat(True)
                self.checkBox.setTristate(False)
                self.checkBox.setObjectName("checkBox")
                self.pushButton_entrar = QtWidgets.QPushButton(self.login)
                self.pushButton_entrar.setEnabled(True)
                self.pushButton_entrar.setGeometry(QtCore.QRect(180, 440, 100, 35))
                self.pushButton_entrar.setMaximumSize(QtCore.QSize(100, 35))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(11)
                self.pushButton_entrar.setFont(font)
                self.pushButton_entrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.pushButton_entrar.setFocusPolicy(QtCore.Qt.StrongFocus)
                self.pushButton_entrar.setStyleSheet("QPushButton{\n"
        "    background-color: rgb(53, 53, 53);\n"
        "    color: white;\n"
        "    border-radius: 10px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    background-color: rgb(117, 117, 117);\n"
        "}\n"
        "QPushButton:pressed {\n"
        "    background-color: rgb(40, 40, 40);\n"
        "}")
                self.pushButton_entrar.setObjectName("pushButton_entrar")
                self.imagem = QtWidgets.QFrame(self.login)
                self.imagem.setGeometry(QtCore.QRect(20, 50, 421, 221))
                self.imagem.setMaximumSize(QtCore.QSize(450, 300))
                self.imagem.setStyleSheet("QFrame {\n"
        "    background-image: url(:/imagem_logo/Logo_Grand_Chase_Chaos.png);\n"
        "    background-position: center;\n"
        "    background-repeat: no-repeat;\n"
        "}")
                self.imagem.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.imagem.setFrameShadow(QtWidgets.QFrame.Raised)
                self.imagem.setObjectName("imagem")
                self.horizontalLayout.addWidget(self.login)
                self.verticalLayout.addWidget(self.frame_3)
                self.footer = QtWidgets.QFrame(self.centralwidget)
                self.footer.setMaximumSize(QtCore.QSize(16777215, 35))
                self.footer.setStyleSheet("")
                self.footer.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
                self.footer.setObjectName("footer")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.footer)
                self.verticalLayout_2.setContentsMargins(0, 0, 10, 0)
                self.verticalLayout_2.setSpacing(0)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.label = QtWidgets.QLabel(self.footer)
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label.setFont(font)
                self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
                self.label.setObjectName("label")
                self.verticalLayout_2.addWidget(self.label)
                self.verticalLayout.addWidget(self.footer)
                MainWindow.setCentralWidget(self.centralwidget)


                #
                #FUNCTIONS
                #

                #Botão de fechar o popup
                self.X.clicked.connect(lambda: self.popup.hide())

                #Frame Hide
                self.popup.hide()

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

                #Botão de Entrar
                self.pushButton_entrar.clicked.connect(self.checkFields)


        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label_error.setText(_translate("MainWindow", "Error"))
                self.X.setText(_translate("MainWindow", "X"))
                self.lineEdit_login.setPlaceholderText(_translate("MainWindow", "Login"))
                self.lineEdit_senha.setPlaceholderText(_translate("MainWindow", "Senha"))
                self.checkBox.setText(_translate("MainWindow", "Salvar"))
                self.pushButton_entrar.setText(_translate("MainWindow", "Entrar"))
                self.label.setText(_translate("MainWindow", "Created by: Maurício R. dos Santos"))
        import files_rc


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
